### ISSUE TITLE
Object index problem?

### ISSUE THREAD

**Issue by twalmsley** [MODLanguage/java-interpreter#14]
This input:
```
?=one:two:three

test1=%0
test2=%1
test3=%2
test4=%3
test5=%4
test6=%5
test7=%6
test8=%7
test9=%8
```
produces (in the playground):
```
[
    {
        "test1": "one"
    },
    {
        "test2": "two"
    },
    {
        "test3": "three"
    },
    {
        "test4": "one"
    },
    {
        "test5": "two"
    },
    {
        "test6": "three"
    },
    {
        "test7": "%6"
    },
    {
        "test8": "%7"
    },
    {
        "test9": "%8"
    }
]
```
But I would expect `%3` onwards to raise an error.

**Comment by alexdalitz** [comment]
I agree that test4 test5 and test6 are wrong, but why should they raise an error? Should they not follow the test7, test8 and test9 example?

Thanks!

**Comment by alexdalitz** [comment]
@elliottinvent any comment on this please?

**Comment by elliottinvent** [comment]
I’d expect this:

``
[
    {
        "test1": "one"
    },
    {
        "test2": "two"
    },
    {
        "test3": "three"
    },
    {
        "test4": "%3"
    },
    {
        "test5": "%4"
    },
    {
        "test6": "%5"
    },
    {
        "test7": "%6"
    },
    {
        "test8": "%7"
    },
    {
        "test9": "%8"
    }
]
``

We’ve previously said that any object references (using object index or otherwise) that refer to objects that don’t exist should print the reference as a string. 

Although perhaps we should change this behaviour so that it’s blank?

**Comment by alexdalitz** [comment]
I prefer the output as @elliottinvent  has it - this is also what the current version of the Interpreter does
