### ISSUE TITLE
punydecode method not working

### ISSUE THREAD

**Issue by elliottinvent** [MODLanguage/java-interpreter#22]
See https://modl.uk/specification#encoding-for-ascii-systems, the example doesn't work:

```
(name=`e1afmkfd`.p;department=` -7sbcecqbdsccxfizhcp6b8ah`.p)
```
Should output:
```
{
    "name": "пример",
    "department": "обслуживание клиентов"
}
```
But doesn't, this is output:
```
{
    "name": "e1afmkfd.p",
    "department": " -7sbcecqbdsccxfizhcp6b8ah.p"
}
```

**Comment by alexdalitz** [comment]
{"input": "?=`e1afmkfd`:` -7sbcecqbdsccxfizhcp6b8ah`;(name=%0.p;department=%1.p)",
  "minimised_modl": "?=`e1afmkfd`:` -7sbcecqbdsccxfizhcp6b8ah`;(name=%0.p;department=%1.p)",
  "expected_output": "{\"name\":\"пример\",\"department\":\"обслуживание клиентов\"}"
}

**Comment by elliottinvent** [comment]
Yeah, good point, that works.

My example doesn't work because we're calling a method on a string, which is something we only recently requested @twalmsley to take on. 

For reference, this works too:
```
_one=`e1afmkfd`
_two=` -7sbcecqbdsccxfizhcp6b8ah`
(
   name=%one.p
   department=%two.p
)
```

**Comment by twalmsley** [comment]
Added a base_test for this and fixed the Ruby interpreter.

**Comment by twalmsley** [comment]
Fixed.
