### ISSUE TITLE
No way to include grave in a value

### ISSUE THREAD

**Issue by elliottinvent** [MODLanguage/java-interpreter#23]
There doesn't seem to be any way to include a grave in a value:

```
test=This is a `test`
```
->
```
{
    "test": "This is a test"
}
```
Escaping doesn't work either, using backslash:
```
test=This is a \`test\`
```
->
```
{
    "test": "This is a test"
}
```
Or using tilde:
```
test=This is a ~`test~`
```
->
```
{
    "test": "This is a test"
}
```

Grave should appear in the output if it's escaped with either `\` or `~`,

**Comment by alexdalitz** [comment]
I _think_ what’s happening is that we’re replacing escaped graves :

replacements.put("~`", "`");

 - and then removing them :

// 1 : Find all parts of the sting that are enclosed in graves, e.g `test` where neither of the graves is prefixed with an escape character ~ (tilde) or \ (backslash).
List<String> graveParts = getGravePartsFromString(stringToTransform);
However, by the time we get there, we’ve already replaced the escaped grave with a grave, so they’re taken out.

I could, of course, be wrong - but I _think_ that’s what’s happening...

**Comment by twalmsley** [comment]
Updated to defer string substitution to the end of interpretation.
Added a base_test.
Fixed.
