### ISSUE TITLE
Use file cache on load error

### ISSUE THREAD

**Issue by elliottinvent** [MODLanguage/java-interpreter#30]
At the moment we cached files we've previously `load`ed. If the file is unavailbale due to server downtime or another reason, we should use the cached file for as long as possible upto maybe 7 days. At the moment, when the one hour cache expires and the file is unavailable the `load` fails.

**Comment by twalmsley** [comment]
Now tries to use the cached copy on load failure, this will only work if there has been a recent-ish load of the same file.
