### ISSUE TITLE
Strings Interpreted Twice

### ISSUE THREAD

**Issue by twalmsley** [MODLanguage/java-interpreter#6]
String substitution is performed twice for some reason (probably a bug), so for input such as this:
```
		test=(a=b=c=d=f)
		test=%test>a>b>c>d
```		
The second line is first transformed to "test=f" then the second invocation tries to use "test=f" as the source of the reference "%test>a>b>c>d", and fails with an exception.
This bug is only apparent when the value of a key is redefined, i.e. 'test' in this case.

**Comment by alexdalitz** [comment]
Yes, it is being interpreted twice. I'm not sure why just now.

However, I do wonder if this should even be valid MODL?

**Comment by alexdalitz** [comment]
Ok - we're going to disallow self-referential assignation in the spec. So this is not valid MODL :)

@elliottinvent Can you update the spec please.

I will add this to the tests to make sure an interpreter error is raised.

Thanks!

**Comment by twalmsley** [comment]
Makes sense. I was trying all sorts to break things and only raised this to highlight the double interpreter call issue.

**Comment by alexdalitz** [comment]
Yes - and thanks!

I think, however, that the self-referential thing _caused_ the double interpreter call.

I think we could get into an awful mess (somehow) by self-referential assignment, so it's easiest just to ban it...

**Comment by elliottinvent** [comment]
I'm going to ban this in the spec, so @twalmsley please test that the interpreter raises an error and then close this issue.

**Comment by twalmsley** [comment]
The fix for this makes the grammar tests invalid - the ones that use `a.modl`, `b.modl`, and `c.modl`. I'll update the test files and corresponding test so that they aren't self-referential.

**Comment by elliottinvent** [comment]
This returns `null`:

```
test=(a=1)
test=%test>a
```

If we're banning this, we need to return an error.

However, it seems a bit inconsistent because this works:

```
_test=foo[1;2]
test=`%test>foo>0`test
```
=>
```
{
    "test": "1test"
}
```
And so does this:
```
_test=1
test=`%test`test
```
Same result.

By banning self-referential assignment I thought we were making any version of `test=%test...` invalid?

**Comment by twalmsley** [comment]
After discussions with @elliottinvent we agreed to leave self-references in the language, which means there are two bugs to fix here. The first is the double evaluation of references in the original comment above, and the second is the one where this results in null:
```
test=(a=1)
test=%test>a
```

**Comment by twalmsley** [comment]
I can't reproduce the double interpretation problem - looking at the code it is part of a strategy where it retries if the interpreter throws a RequireRestart exception, because it has more information the second time around. If the second time fails or a different exception is thrown then the Modl is invalid and interpretation stops.

This just leaves the above test case failures to fix.

**Comment by twalmsley** [comment]
Fixed.
