### ISSUE TITLE
Expression Evaluation

### ISSUE THREAD

**Issue by twalmsley** [MODLanguage/java-interpreter#7]
The following parses correctly, but isn't clear what it means (it sets c to '-1' when I think it should be '0'):
```
		a=3
		b=4
		c=3
		d=3
		e={a=b|c|d?
			0
		/a>b?
			1
		/?
			-1
		}
```
This parses correctly but throws a NullPointerException:
```
		a=3
		b=4
		c=3
		d=3
		e={a=b|a=c|a=d?
			0
		/a>b?
			1
		/?
			-1
		}
```

**Comment by twalmsley** [comment]
There seems to be a general problem with expression evaluation at the moment because the current version of the java interpreter is giving different results to the sandbox. E.g. this:
```
a=1;b=2;b={{a=1}|{b=2}?true/?false}
```
results in:
```
[
    {
        "a": 1
    },
    {
        "b": 2
    },
    {
        "b": true
    }
]
```
in the sandbox, but the java interpreter gives this:
```
[ {
  "a" : 1
}, {
  "b" : 2
}, {
  "b" } ]
```

**Comment by alexdalitz** [comment]
This is working in my current (uncommitted) Interpreter, so I'm going to close it.

Thanks!
